language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="settings.travis"
  - SECRET_KEY="t-l@zgp9zyog3t%j5ee)1rqd600_(u9mz@b_8$bkohr@3d7@on"
  - ALLOWED_HOSTS="46.101.184.139"

services:
  - postgresql

script:
  - python manage.py test
