language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE=settings.travis

script:
  - sudo service postgresql status
  - sudo netstat -nl | grep postgres
  - python manage.py test
