# Generated by Django 3.0 on 2020-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default='default@gmail.com', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
