# Generated by Django 3.0 on 2020-05-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200527_1952'),
        ('accounts', '0006_auto_20200527_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
