# Generated by Django 3.0.7 on 2020-07-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image_url', models.URLField(default=None)),
                ('fat_100g', models.FloatField(default=None)),
                ('saturated_fat_100g', models.FloatField(default=None)),
                ('sugars_100g', models.FloatField(default=None)),
                ('salt_100g', models.FloatField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purbeurre.Category')),
            ],
        ),
    ]
