# Generated by Django 3.0.3 on 2020-06-13 11:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purbeurre', '0003_auto_20200612_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Favourite',
        ),
    ]
