# Generated by Django 3.0.3 on 2020-06-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0004_auto_20200613_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
